structure(list(url = "https://www.ebi.ac.uk/Tools/hmmer/search/hmmscan", 
    status_code = 400L, headers = structure(list(server = "Apache/2.4.6 (CentOS)", 
        vary = "Content-Type", `cache-control` = "max-age=0", 
        `content-type` = "text/xml; charset=UTF-8", `strict-transport-security` = "max-age=0", 
        date = "Tue, 19 Jul 2022 12:54:53 GMT", `access-control-max-age` = "1000", 
        expires = "Tue, 19 Jul 2022 12:54:53 GMT", `access-control-allow-origin` = "*", 
        connection = "close", `set-cookie` = "REDACTED", `access-control-allow-methods` = "HEAD, POST, GET, OPTIONS, DELETE, PUT", 
        `access-control-allow-headers` = "x-requested-with, Content-Type, origin, authorization, accept, client-security-token", 
        `content-length` = "88"), class = c("insensitive", "list"
    )), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(server = "Apache/2.4.6 (CentOS)", 
            vary = "Content-Type", `cache-control` = "max-age=0", 
            `content-type` = "text/xml; charset=UTF-8", `strict-transport-security` = "max-age=0", 
            date = "Tue, 19 Jul 2022 12:54:53 GMT", `access-control-max-age` = "1000", 
            expires = "Tue, 19 Jul 2022 12:54:53 GMT", `access-control-allow-origin` = "*", 
            connection = "close", `set-cookie` = "REDACTED", 
            `access-control-allow-methods` = "HEAD, POST, GET, OPTIONS, DELETE, PUT", 
            `access-control-allow-headers` = "x-requested-with, Content-Type, origin, authorization, accept, client-security-token", 
            `content-length` = "88"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_www.ebi.ac.uk", 
        flag = FALSE, path = "/", secure = FALSE, expiration = structure(1658926493, class = c("POSIXct", 
        "POSIXt")), name = "hmmerserver_session", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("<opt>\n  <data>\n    <hmmdb>pdb is not a supported hmm database.</hmmdb>\n  </data>\n</opt>\n"), 
    date = structure(1658235293, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3e-05, 
    connect = 0.052548, pretransfer = 0.230232, starttransfer = 0.230241, 
    total = 0.372279)), class = "response")
